// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqyZ2rBQF5ig5AIoWrquaXfXydCxvt4o',
    appId: '1:611410587495:android:1c2348fc1b27b67aab89c2',
    messagingSenderId: '611410587495',
    projectId: 'youme-28e40',
    storageBucket: 'youme-28e40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzAE0Fzpu0_Oj69wwmkO4Who9C2tiE0vY',
    appId: '1:611410587495:ios:5f55848ed3a23378ab89c2',
    messagingSenderId: '611410587495',
    projectId: 'youme-28e40',
    storageBucket: 'youme-28e40.appspot.com',
    androidClientId:
        '611410587495-alclrf0aet3ue7ibo7qfs7pae6omqkcr.apps.googleusercontent.com',
    iosClientId:
        '611410587495-hkh0u2p81ccnoqv6bu3runq0t26ajq7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.youme',
  );
}
